; meta (:version 1.0 :package "RADIANCE-CORE")
((:interfaces (:admin . "r-simple-admin") (:auth . "r-simple-auth")
  (:ban . "r-simple-ban") (:cache . "r-simple-cache")
  (:data-model . "r-simple-model") (:database . "i-lambdalite")
  (:relational-database . "i-sqlite") (:logger . "i-verbose")
  (:mail . "i-smtp") (:profile . "r-simple-profile") (:rate . "r-simple-rate")
  (:server . "i-hunchentoot") (:session . "r-simple-sessions")
  (:user . "r-simple-users"))
 (:versions
  . [hash-table equal ("radiance-core" :|2.2.0|) ("i-verbose" :|1.0.0|)
     ("i-hunchentoot" :|1.1.0|) ("r-clip" :|1.0.0|) ("r-welcome" :|1.0.0|)
     ("r-simple-errors" :|1.0.0|) ("asteroid" :|0.0.0|)
     ("r-data-model" :|1.0.1|) ("i-lambdalite" :|1.0.0|) ("i-log4cl" :|1.0.0|)
     ("r-simple-users" :|1.0.1|) ("r-simple-sessions" :|1.0.1|)
     ("r-simple-rate" :|1.0.0|) ("r-simple-profile" :|1.0.0|)
     ("r-simple-auth" :|1.0.0|) ("r-ratify" :|1.0.0|)])
 (:domains "radiance" "localhost" "asteroid")
 (:startup :r-simple-errors :r-simple-sessions) (:routes)
 (:debugger . :if-swank-connected))